// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIVapQpQBgpTzKt_QRugkflZrJjvifso',
    appId: '1:1082535503975:android:0f39e0382cccaad8270cc2',
    messagingSenderId: '1082535503975',
    projectId: 'classicart-esoft',
    databaseURL: 'https://classicart-esoft-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classicart-esoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBux7iVcXu7EG3fh91Ek8dAcKxwc5T7QeQ',
    appId: '1:1082535503975:ios:1a2195da141d3929270cc2',
    messagingSenderId: '1082535503975',
    projectId: 'classicart-esoft',
    databaseURL: 'https://classicart-esoft-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classicart-esoft.appspot.com',
    iosBundleId: 'com.example.airtualShowroomProj',
  );
}
